=== DevikaS/gdam/monitoring/src/main/resources/xml/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Script" type="ScriptType"/>
    <xs:complexType name="ScriptType" mixed="true">
        <xs:sequence>
            <xs:element name="applicationURL" type="xs:string"/>
            <xs:element name="action" type="ActionType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ActionType">
        <xs:sequence>
            <xs:element name="method">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="authSSO"/>
                        <xs:enumeration value="logoutSSO"/>
                        <xs:enumeration value="getProject"/>
                        <xs:enumeration value="findProjects"/>
                        <xs:enumeration value="findFoldersContent"/>
                        <xs:enumeration value="findAssets"/>
                        <xs:enumeration value="findReels"/>
                        <xs:enumeration value="getReel"/>
                        <xs:enumeration value="getContent"/>
                        <xs:enumeration value="getAsset"/>
                        <xs:enumeration value="downloadFile"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="argument" type="ArgumentType" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="assertion" type="AssertionType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ArgumentType">
        <xs:sequence>
            <xs:element name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="String"/>
                        <xs:enumeration value="Search"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="value" type="xs:string" minOccurs="0"/>
            <xs:element name="searchValue" type="SearchValueType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SearchValueType">
        <xs:sequence>
            <xs:element name="query" type="xs:string" minOccurs="0"/>
            <xs:element name="page" type="xs:int" minOccurs="0"/>
            <xs:element name="size" type="xs:int" minOccurs="0"/>
            <xs:element name="sort" type="xs:string" minOccurs="0"/>
            <xs:element name="order" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="ASC"/>
                        <xs:enumeration value="DESC"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="deleted" type="xs:boolean" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AssertionType">
        <xs:sequence>
            <xs:element name="size" type="xs:int" minOccurs="0"/>
            <xs:element name="sizeMin" type="xs:int" minOccurs="0"/>
            <xs:element name="sizeMax" type="xs:int" minOccurs="0"/>
            <xs:element name="name" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== DevikaS/gdam/monitoring/src/main/resources/xml/find-projects.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Script xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <applicationURL>https://a5.adstream.com</applicationURL>
    <action>
        <method>authSSO</method>
        <argument>
            <type>String</type>
            <value>monitoring@adstream.com</value>
        </argument>
        <argument>
            <type>String</type>
            <value>6Welcome!</value>
        </argument>
    </action>
    <action>
        <method>findProjects</method>
        <argument>
            <type>Search</type>
            <searchValue>
                <query>_cm.common.name:monitoring_project</query>
            </searchValue>
        </argument>
        <assertion>
            <sizeMin>1</sizeMin>
        </assertion>
    </action>
    <action>
        <method>getProject</method>
        <argument>
            <type>String</type>
            <value>51f90159e4b0d99fd28beba3</value>
        </argument>
        <assertion>
            <name>monitoring_project</name>
        </assertion>
    </action>
    <action>
        <method>logoutSSO</method>
    </action>
</Script>

=== DevikaS/gdam/monitoring/src/main/resources/xml/find-assets.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Script xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <applicationURL>https://a5.adstream.com</applicationURL>
    <action>
        <method>authSSO</method>
        <argument>
            <type>String</type>
            <value>monitoring@adstream.com</value>
        </argument>
        <argument>
            <type>String</type>
            <value>Password1</value>
        </argument>
    </action>
    <action>
        <method>findAssets</method>
        <argument>
            <type>String</type>
            <!-- 'My Assets' category id -->
            <value>50079d4adb016b1bf9952658</value>
        </argument>
        <argument>
            <type>Search</type>
        </argument>
        <assertion>
            <sizeMin>1</sizeMin>
        </assertion>
    </action>
    <action>
        <method>getAsset</method>
        <argument>
            <type>String</type>
            <value>533bca9ce4b0e1cb77f5c6e1</value>
        </argument>
        <assertion>
            <name>monitoring_asset.jpg</name>
        </assertion>
    </action>
    <action>
        <method>logoutSSO</method>
    </action>
</Script>
